Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Input/EducationInput.tsx
Hi-Match/src/pages/MyPage/Resume/components/ResumeWrite/Input/EducationInput.tsx

[bomin/merge] :art:add: EducationInput 수정

[bomin/merge] :art:add: EducationInput 수정

---

Hi-Match/src/types/resume.d.ts

[bomin/merge] :art:add: ResumeEdit/SchoolInput 수정 및 resume type 수정

[bomin/merge] :art:add: ResumeEdit/SchoolInput 수정 및 resume type 수정

---

Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Input/SchoolInput.tsx

[bomin/merge] :art:add: ResumeEdit/SchoolInput 수정

[bomin/merge] :art:add: ResumeEdit/SchoolInput 수정

---

Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Input/SchoolInput.tsx
Hi-Match/src/types/resume.d.ts

[dev/merge] :art:add: ResumeEdit/SchoolInput 수정

[dev/merge] :art:add: ResumeEdit/SchoolInput 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx

[bomin/merge] :sparkles:feat: [기업] 사이드바 구현 완료

[bomin/merge] :sparkles:feat: [기업] 사이드바 구현 완료

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx

[bomin/merge] :art:add: BizSidebar 메뉴 수정

[bomin/merge] :art:add: BizSidebar 메뉴 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx

[dev/merge] :art:add: BizSidebar 메뉴 수정

[dev/merge] :art:add: BizSidebar 메뉴 수정

---

Hi-Match/src/pages/Login/LoginForm.tsx

[bomin/merge] :art:add: 기업 로그인 후 링크 수정

[bomin/merge] :art:add: 기업 로그인 후 링크 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx
Hi-Match/src/pages/Login/LoginForm.tsx

[dev/merge] :art:add: 기업 로그인 후 링크 수정

[dev/merge] :art:add: 기업 로그인 후 링크 수정

---

Hi-Match/src/hooks/bookmark/useBookmarkMaxPage.ts
Hi-Match/src/pages/JobPostingDetail/JobPostingDetail.tsx
Hi-Match/src/pages/JobPostingDetail/components/JobSummary.tsx
Hi-Match/src/pages/JobPostingDetail/components/JobSummaryCell.tsx
Hi-Match/src/pages/MyPage/Bookmark/components/BookmarkImage.tsx

[merge / yoonseul] 🎨 add: 사용하지 않는 코드 주석처리

---

Hi-Match/eslint.config.js

[uiseok/merge] ✨feat: eslint unused var 기능 off

[uiseok/merge] ✨feat: eslint unused var 기능 off

---

Hi-Match/src/hooks/bookmark/useBookmarkListSearch.ts
Hi-Match/src/pages/MyPage/Bookmark/UserBookmark.tsx

[uiseok/merge] ✨feat: 북마크 검색 기능 구현 완료

[uiseok/merge] ✨feat: 북마크 검색 기능 구현 완료

---

Hi-Match/src/pages/CompanyInfo/components/AddressInput.tsx
Hi-Match/src/pages/CompanyInfo/components/CompanyInfoForm.tsx
Hi-Match/src/pages/CompanyInfo/components/DescriptionInput.tsx
Hi-Match/src/pages/CompanyInfo/components/EmployeeInput.tsx
Hi-Match/src/pages/CompanyInfo/components/HomePageInput.tsx
Hi-Match/src/pages/CompanyInfo/components/ImageUploadInput.tsx
Hi-Match/src/pages/CompanyInfo/components/IndustryInput.tsx
Hi-Match/src/pages/CompanyInfo/components/LicenseInput.tsx
Hi-Match/src/pages/CompanyInfo/components/ManageNameInput.tsx
Hi-Match/src/pages/CompanyInfo/components/NameInput.tsx
Hi-Match/src/pages/CompanyInfo/components/TagForm.tsx

[bomin/merge] :sparkles:feat:[기업] 기업 정보, 태그 등록 및 수정 구현 완료

[bomin/merge] :sparkles:feat:[기업] 기업 정보, 태그 등록 및 수정 구현 완료

---

Hi-Match/src/constants/index.ts

[bomin/merge] :art:add: constants/index 파일 수정

[bomin/merge] :art:add: constants/index 파일 수정

---

Hi-Match/src/types/company-info.d.ts

[bomin/merge] :art:add: 기업 정보 type 수정

[bomin/merge] :art:add: 기업 정보 type 수정

---

Hi-Match/src/constants/index.ts
Hi-Match/src/types/company-info.d.ts

[dev/merge] :art:add: 기업 정보 type 수정

[dev/merge] :art:add: 기업 정보 type 수정

---

Hi-Match/src/pages/CompanyInfo/components/CompanyInfoForm.tsx

[bomin/merge] :art:add: 기업 정보 입력 Form 수정

[bomin/merge] :art:add: 기업 정보 입력 Form 수정

---

Hi-Match/src/pages/CompanyInfo/components/CompanyInfoForm.tsx
Hi-Match/src/types/company-info.d.ts

[dev/merge] :art:add: 기업 정보 입력 Form 수정

[dev/merge] :art:add: 기업 정보 입력 Form 수정

---

Hi-Match/src/pages/CompanyInfo/CompanyInfo.tsx
Hi-Match/src/pages/CompanyInfo/components/CompanyInfoForm.tsx
Hi-Match/src/types/company-info.d.ts

[dev/merge] :art:add: company info type 이름 변경

[dev/merge] :art:add: company info type 이름 변경

---

Hi-Match/src/pages/CompanyInfo/CompanyInfo.tsx

[bomin/merge] :sparkles:feat: 기업 정보 필수 미입력 시 저장 버튼 비활성화 기능 추가

[bomin/merge] :sparkles:feat: 기업 정보 필수 미입력 시 저장 버튼 비활성화 기능 추가

---

Hi-Match/src/pages/MyPage/Bookmark/components/BookmarkImage.tsx
Hi-Match/src/pages/MyPage/Home/components/ApplicationList.tsx
Hi-Match/src/pages/MyPage/Home/components/BookmarkList.tsx
Hi-Match/src/pages/MyPage/Home/components/PersonalityTest.tsx
Hi-Match/src/pages/MyPage/Home/components/ResumeList.tsx
Hi-Match/src/routes/AppRoutes.tsx

[uiseok/merge] ✨feat: 마이페이지 myhome 부분 API와 연동하여 ui 출력 완료

[uiseok/merge] ✨feat: 마이페이지 myhome 부분 API와 연동하여 ui 출력 완료

---

Hi-Match/index.html
Hi-Match/public/Hi-Match.svg
Hi-Match/src/components/Header/Header.tsx
Hi-Match/src/components/Sidebar/UserSidebar.tsx
Hi-Match/src/layout/AuthLayout.tsx

[bomin/merge] :lipstick:style: 로고 변경

[bomin/merge] :lipstick:style: 로고 변경

---

Hi-Match/src/pages/RecruitPosting/components/Form/RecruitPostForm.tsx

[bomin/merge] :art:add: 기업 공고 등록 workStartTime & workEndTime  타입 수정

[bomin/merge] :art:add: 기업 공고 등록 workStartTime & workEndTime  타입 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx
Hi-Match/src/pages/Main/MainPage.tsx

[bomin/merge] :lipstick:style: 메인페이지 스타일 수정/기업 사이드바 스타일 수정

[bomin/merge] :lipstick:style: 메인페이지 스타일 수정/기업 사이드바 스타일 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx
Hi-Match/src/pages/Main/MainPage.tsx
Hi-Match/src/pages/RecruitPosting/components/Form/RecruitPostForm.tsx

[dev/merge] :lipstick:style: 메인페이지 스타일 수정/기업 사이드바 스타일 수정

[dev/merge] :lipstick:style: 메인페이지 스타일 수정/기업 사이드바 스타일 수정

---

Hi-Match/src/components/Sidebar/UserSidebar.tsx
Hi-Match/src/routes/AppRoutes.tsx
Hi-Match/src/styles/index.css

[bomin/merge] :bug:fix: UserSidebar, AppRoutes, index.css 이전 버전으로 재업로드

[bomin/merge] :bug:fix: UserSidebar, AppRoutes, index.css 이전 버전으로 재업로드

---

Hi-Match/src/components/Sidebar/UserSidebar.tsx

[bomin/merge] :lipstick:style: UserSidebar 메뉴 위치 수정

[bomin/merge] :lipstick:style: UserSidebar 메뉴 위치 수정

---

Hi-Match/src/components/Header/Login.tsx

[bomin/merge] :art:add: Login.tsx 파일 navigate 제거

[bomin/merge] :art:add: Login.tsx 파일 navigate 제거

---

Hi-Match/src/components/Header/Login.tsx
Hi-Match/tsconfig.json

[dev/merge] :art:add: Login.tsx 파일 navigate 제거

[dev/merge] :art:add: Login.tsx 파일 navigate 제거

---

Hi-Match/src/pages/RecruitPosting/components/Input/WorkTypeInput.tsx
Hi-Match/src/utils/dateFormat.ts

[bomin/merge] :art:add: dateFormate 파일, WorkTypeInput 파일 수정

[bomin/merge] :art:add: dateFormate 파일, WorkTypeInput 파일 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx

[bomin/merge] :art:add: [기업] 사이드바 메뉴 추가

[bomin/merge] :art:add: [기업] 사이드바 메뉴 추가

---

Hi-Match/src/pages/Applicants/Applicants.tsx
Hi-Match/src/pages/Applicants/components/ApplicantsForm.tsx
Hi-Match/src/pages/Applicants/components/ApplicantsListForm.tsx
Hi-Match/src/pages/Applicants/components/RecruitForm.tsx
Hi-Match/src/pages/Applicants/components/RecruitFormList.tsx
Hi-Match/src/routes/AppRoutes.tsx
Hi-Match/src/routes/PrivateRoute.tsx

[bomin/merge] :art:add: 비로그인 회원 마이페이지, 회사 페이지 접근 불가

[bomin/merge] :art:add: 비로그인 회원 마이페이지, 회사 페이지 접근 불가

---

Hi-Match/package.json

[bomin/merge] 🎨 add: tiptap image extension 설치 후 package.json 파일 업로드

[bomin/merge] 🎨 add: tiptap image extension 설치 후 package.json 파일 업로드

---

Hi-Match/src/layout/BizLayout.tsx
Hi-Match/src/pages/CompanyIdeal/CompanyIdeal.tsx

[bomin/merge] :lipstick:style: [기업] 인재상 관리 스타일 수정

[bomin/merge] :lipstick:style: [기업] 인재상 관리 스타일 수정

---

Hi-Match/src/hooks/application/useResumeList.ts
Hi-Match/src/pages/JobPostingDetail/components/DeadlineBanner.tsx

상세 페이지 - '지원하기' 버튼을 클릭해서 사용자 정보 조회 및 이력서 조회하고 작성 후 지원이 가능함
-> 비회원인 경우에도 똑같은 로직이 적용되어 에러가 발생했던 것으로 추측
'지원하기' 버튼을 눌러 사용자 정보를 조회하도록 하고, 토큰이 없는 경우 해당 버튼 비활성화

[merge /  yoonseul] :bug:fix: 배포 환경에서 상세 페이지가 렌더링되지 않는 에러 수정

---

Hi-Match/src/components/Footer/Footer.tsx
Hi-Match/src/hooks/application/useJobPostingDetail.ts
Hi-Match/src/pages/JobPostingDetail/JobPostingDetail.tsx
Hi-Match/src/pages/JobPostingDetail/components/CompanyProfileCard.tsx
Hi-Match/src/pages/JobPostingDetail/components/JobSummaryCell.tsx

[bomin/merge] 🎨add: 공고 상세 조회 시 기업 정보 api 수정 및 스타일링 수정 / Footer 전화번호, 이메일 추가

[bomin/merge] 🎨add: 공고 상세 조회 시 기업 정보 api 수정 및 스타일링 수정 / Footer 전화번호, 이메일 추가

---

Hi-Match/src/pages/Login/LoginPage.tsx

[bomin/merge] :art:add: 로그인 페이지 진입 시 스크롤 최상단으로 이동

[bomin/merge] :art:add: 로그인 페이지 진입 시 스크롤 최상단으로 이동

---

Hi-Match/src/pages/CompanyHome/CompanyHome.tsx
Hi-Match/src/pages/Login/LoginForm.tsx
Hi-Match/src/routes/AppRoutes.tsx

[bomin/merge] :art:add: [기업] 로그인 후 기업 정보 페이지로 이동

[bomin/merge] :art:add: [기업] 로그인 후 기업 정보 페이지로 이동

---

Hi-Match/src/pages/CompanyHome/CompanyHome.tsx
Hi-Match/src/pages/Login/LoginForm.tsx
Hi-Match/src/pages/Login/LoginPage.tsx
Hi-Match/src/routes/AppRoutes.tsx

[dev/merge] :art:add: [기업] 로그인 후 기업 정보 페이지로 이동

[dev/merge] :art:add: [기업] 로그인 후 기업 정보 페이지로 이동

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx
Hi-Match/src/pages/RecruitPosting/components/Form/CoverLetterFormList.tsx
Hi-Match/src/pages/RecruitPosting/components/Form/CoverLetterFormListEdit.tsx

[bomin/merge] 🎨add: [기업] 공고 등록 및 수정 시 자기소개서 문항 최대 3개로 제한 / 기업 사이드바 로고 링크 수정

[bomin/merge] 🎨add: [기업] 공고 등록 및 수정 시 자기소개서 문항 최대 3개로 제한 / 기업 사이드바 로고 링크 수정

---

Hi-Match/src/pages/MyPage/Resume/ResumeEdit/ResumeEdit.tsx
Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Form/ResumeEditForm.tsx
Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Input/AddressInput.tsx
Hi-Match/src/pages/MyPage/Resume/components/ResumeEdit/Input/ProfileInfoInput.tsx

[bomin/merge] :art:add: [개인] 이력서 수정 시 필수 입력 데이터 미입력 시 수정 완료 버튼 비활성화 추가

[bomin/merge] :art:add: [개인] 이력서 수정 시 필수 입력 데이터 미입력 시 수정 완료 버튼 비활성화 추가

---

Hi-Match/src/components/Pagination/Pagination.tsx

[bomin/merge] :art:add: 페이지네이션 컴포넌트 숫자 겹침 수정 및 스타일 수정

[bomin/merge] :art:add: 페이지네이션 컴포넌트 숫자 겹침 수정 및 스타일 수정

---

Hi-Match/src/components/Sidebar/BizSidebar.tsx
Hi-Match/src/components/Sidebar/UserSidebar.tsx

[bomin/merge] :art:add: 로그아웃 버튼 클릭 시 실행 되는 코드 순서 변경

[bomin/merge] :art:add: 로그아웃 버튼 클릭 시 실행 되는 코드 순서 변경

---

Hi-Match/src/pages/CompanyInfo/components/TagForm.tsx

[bomin/merge] :art:add: [기업] 회사 정보 태그 최대 30개로 수정

[bomin/merge] :art:add: [기업] 회사 정보 태그 최대 30개로 수정
